# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoteCompiler < Formula
  desc "A cross-platform Go CLI tool for compiling markdown notes"
  homepage "https://github.com/jahabrewer/note-compiler"
  version "1.0.2"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/jahabrewer/note-compiler/releases/download/v1.0.2/obsidian-tools_Darwin_x86_64.tar.gz"
      sha256 "f9d8efb8bc18d093147520175ed59a06fa222ac68fcd3aa68b98e2d66d740de5"

      def install
        bin.install "note-compiler"
      end
    end
    on_arm do
      url "https://github.com/jahabrewer/note-compiler/releases/download/v1.0.2/obsidian-tools_Darwin_arm64.tar.gz"
      sha256 "dd5f6abbdff009947cc85ff298350f4236f9a63b46374c41a1800911dd2a7111"

      def install
        bin.install "note-compiler"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahabrewer/note-compiler/releases/download/v1.0.2/obsidian-tools_Linux_x86_64.tar.gz"
        sha256 "7d0163b9da8bfec3f7af7262655e9138c1f81250b69e85ccb441a79b8da2acf6"

        def install
          bin.install "note-compiler"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jahabrewer/note-compiler/releases/download/v1.0.2/obsidian-tools_Linux_armv6.tar.gz"
        sha256 "c1b610d2e39b9c4433b7c692a1e7dd31ca4e6a29daf732a53aea90f003423658"

        def install
          bin.install "note-compiler"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahabrewer/note-compiler/releases/download/v1.0.2/obsidian-tools_Linux_arm64.tar.gz"
        sha256 "1fb36b81f8da47a15ed38207685c7435656cfc833ad5923e0617598f469f5add"

        def install
          bin.install "note-compiler"
        end
      end
    end
  end

  test do
    system "#{bin}/note-compiler", "--version"
  end
end
